name: rack_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Router
  go_router: ^7.0.1

  # DI
  get_it: ^7.6.0

  # Remote API
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1

  # Codegen
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0

  # State management
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  # Localization
  intl: ^0.17.0

  # Other
  google_fonts: ^4.0.4
  sliver_tools: ^0.2.10

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  retrofit_generator: ^4.0.3

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


